#+STARTUP: showeverything

* Cheat
A small utility to register and create cheatsheets based on org-mode.

** Provided cheatsheets
| Name            | Description |
|-----------------+-------------|
| JSDoc           |             |
| Magit           |             |
| AsciiDoc        |             |
| Org mode        |             |
| Org mode syntax |             |

** Installation
The package has not yet been published to MELPA yet so you'll have to install it manually or use [[https://framagit.org/steckerhalter/quelpa][quelpa]].
#+BEGIN_SRC elisp
(quelpa '(cheat :fetcher github :repo "pbellon/cheat"))
(require 'cheat)
(cheat/reload-sheets)

;; Or, if you have use-package & quelpa-use-package
(use-package
    :quelpa (cheat :fetcher github :repo "pbellon/cheat")
    :config
    (cheat/reload-sheets))
#+END_SRC

** Usage
*** Open a cheatsheet 
~M-x RET cheat RET <command>~

*** Cheasheet commands
All cheatsheets are accessible through interactive functions with ~cheat/<command>~ format. For instance ~cheat/adoc~  opens asciidoc cheatsheet.

*** Register a new cheatsheets folder

#+BEGIN_SRC elisp
;; Register your cheatsheets in the cheat/sheets list
(add-to-list 'cheat/sheets-folders "path/to/my/cheatsheets/")
;; Launch initialization of the utility, it will create the ~cheat/custom~ interactive function.
(cheat/reload-sheets)
#+END_SRC

*** Filter cheatsheets by categories

You can change which set of cheatsheet is loaded by default by the package by changing =cheat/categories= value: 

#+BEGIN_SRC elisp
(setq cheat/categories '("JavaScript" "Emacs" "CLI"))
#+END_SRC

You can see all available categories by calling ~cheat/list-categories~ interactive function.

*** Add a new cheatsheet file / folder

All sheets files must be located under a folder included in =cheat/sheets-folder=. 

They must have an header like bellow:

#+BEGIN_SRC org
#+TITLE: My title
#+COMMAND: mycommand
#+DESCRIPTION: Optional description
#+CATEGORY: Category
#+END_SRC

You can then reload the cheatsheets by calling ~cheat/reload-sheets~ interactive function. However take care that your new cheatsheet's category is listed under =cheat/categories=
